version: '3.8'
services: 
    phantom-app-be:
      container_name: phantom-be-app
      build:
        dockerfile: Dockerfile
      volumes:
        - '/usr/app'
        - '/usr/app/node_modules'
      ports:
        - 4000:4000
      environment:
        - CHOKIDAR_USEPOLLING=true
    