name: node js CI/CD
on:
  push:
    branches: [develop, ch-setup-continous-continous-integration-#18]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js "16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm i
      - run: npm run build --if-present
  coverage:
    needs: [build]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js "16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm i
      - uses: paambaati/codeclimate-action@v2.5.0
        env:
          CI: "true"
          CC_TEST_REPORTER_ID: a3b71148e748619b5c2ad04e1e6afd394e9fbf8f1dfb04428d984aaef7c17ee2
        with:
          debug: true
          coverageCommand: npm run coverage