name: CI/CD

on:
  push:
    branches: [ ch-setup-continous-continous-integration-#18 ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
      codecov:
        token: f3068969-f4f8-42f3-be26-3f19aea87b7e

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1


    - name: Build
      run: npm run build 



